services:
  db:
    image: paradedb/paradedb:latest-pg18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: django_docs
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
