# Generated by Django 5.2.12 on 2026-03-19 14:01

import paradedb.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='section_title',
            field=models.CharField(blank=True, help_text='검색 성능 향상을 위한 섹션 제목 데이타 (비정규화)', max_length=512),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content',
            field=models.TextField(help_text='분할된 텍스트 본문'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024, help_text='BGE-M3 1024차원 벡터 임베딩'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='overlap_index',
            field=models.IntegerField(default=0, help_text='중첩 분할 시의 인덱스'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='token_count',
            field=models.IntegerField(help_text='대략적인 토큰 수'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(help_text='문서 카테고리 (예: Tutorials, Reference)', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_path',
            field=models.CharField(help_text='로컬 파일 시스템의 절대 경로', max_length=1024),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True, help_text='공식 Django 문서 웹 URL', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='검색 활성화 상태', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='target_version',
            field=models.CharField(help_text='대상 Django 버전 (예: 5.2)', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(help_text='문서의 제목 (YAML Front Matter 또는 파일명)', max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='level',
            field=models.IntegerField(help_text='헤더 깊이 (1: H1, 2: H2, 3: H3)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(help_text='문서 내 섹션 순서'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(help_text='섹션 제목 (헤더 텍스트)', max_length=512),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=paradedb.indexes.BM25Index(fields={'content': {}, 'id': {}, 'section_title': {}}, key_field='id', name='chunk_bm25_idx'),
        ),
    ]
