# Generated by hand on 2026-03-18

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='section_title',
            field=models.CharField(blank=True, help_text='검색 성능 향상을 위한 섹션 제목 데이타 (비정규화)', max_length=512),
        ),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_search;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_search;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_chunk_bm25 ON documents_chunk 
            USING bm25 (id, content, section_title) 
            WITH (key_field = 'id');
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_chunk_bm25;"
        ),
    ]
