# Generated by Django 5.2.12 on 2026-03-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_chunk_section_title_alter_chunk_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='multi_vector_low_dim',
            field=models.BinaryField(blank=True, help_text='Late Interaction 리랭킹용 압축 멀티 벡터 (128차원, int8). 포맷: [TokenCount(2B)][VectorData]', null=True),
        ),
    ]
