# Generated by Django 5.2.12 on 2026-03-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_chunk_multi_vector_low_dim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='multi_vector_low_dim',
            field=models.BinaryField(blank=True, help_text='Late Interaction용 압축 멀티 벡터. 포맷: [TokenCount(2B)][VectorData]', null=True),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='section_title',
            field=models.CharField(blank=True, help_text='검색 성능 향상을 위한 섹션 제목 데이타 (비정규화)', max_length=1024),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(help_text='문서의 제목 (YAML Front Matter 또는 파일명)', max_length=512),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(help_text='섹션 제목 (헤더 텍스트)', max_length=1024),
        ),
    ]
