import asyncio
import os
import sys
from pathlib import Path

import django

# Django 설정 로드 (import 이전에 수행되어야 함)
# src 디렉토리를 파이썬 경로에 추가
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(str(BASE_DIR / "src"))

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings")
django.setup()

# ruff: noqa: E402 (Django setup 이후 임포트를 허용)
from documents.services.search import get_search_service

# US3: 골든 데이터셋 정의 (Django ORM Cookbook 기반 현실적 질문 20선)
GOLDEN_DATASET = [
    # 1. Basic Filtering (AND/OR/NOT)
    {
        "query": "How to perform OR queries in Django ORM?",
        "expected_keywords": ["Q objects", "| operator", "OR condition"],
        "category": "Basic Filtering",
    },
    {
        "query": "How to filter results with NOT conditions?",
        "expected_keywords": ["exclude()", "~Q", "NOT query"],
        "category": "Basic Filtering",
    },
    {
        "query": "How to perform AND queries using filter() and Q?",
        "expected_keywords": ["filter", "Q objects", "& operator"],
        "category": "Basic Filtering",
    },
    # 2. Aggregation & Annotation
    {
        "query": "How to calculate the average price of products?",
        "expected_keywords": ["Avg", "aggregate", "Avg("],
        "category": "Aggregation",
    },
    {
        "query": "How to count records grouped by a specific field?",
        "expected_keywords": ["annotate", "Count", "values().annotate"],
        "category": "Aggregation",
    },
    {
        "query": "Find the maximum and minimum value in a QuerySet.",
        "expected_keywords": ["Max", "Min", "aggregate"],
        "category": "Aggregation",
    },
    # 3. Joins & Relationships
    {
        "query": "How to filter by fields in a related model (Join)?",
        "expected_keywords": ["__", "double underscore", "filter(related__field)"],
        "category": "Relationships",
    },
    {
        "query": "The difference between select_related and prefetch_related.",
        "expected_keywords": ["JOIN", "IN query", "performance optimization"],
        "category": "Relationships",
    },
    {
        "query": "How to filter using One-to-One relationship fields?",
        "expected_keywords": ["OneToOneField", "reverse relationship"],
        "category": "Relationships",
    },
    # 4. Advanced Querying
    {
        "query": "How to write Subqueries in Django ORM?",
        "expected_keywords": ["Subquery", "OuterRef", "Subquery("],
        "category": "Advanced",
    },
    {
        "query": "Using Exists in subquery expressions.",
        "expected_keywords": ["Exists", "Subquery", "Exists("],
        "category": "Advanced",
    },
    {
        "query": "How to use F expressions for field comparisons?",
        "expected_keywords": ["F()", "F objects", "atomic update"],
        "category": "Advanced",
    },
    # 5. Ordering & Slicing
    {
        "query": "How to order results in a case-insensitive manner?",
        "expected_keywords": ["Lower", "Func", "order_by"],
        "category": "Ordering",
    },
    {
        "query": "Ordering by a field in a related model.",
        "expected_keywords": ["order_by('related__field')", "__"],
        "category": "Ordering",
    },
    # 6. Database Functions & Raw SQL
    {
        "query": "How to execute raw SQL queries in Django?",
        "expected_keywords": ["RawSQL", "Manager.raw()", "connection.cursor"],
        "category": "Raw SQL",
    },
    {
        "query": "How to use database functions like Coalesce or Concat?",
        "expected_keywords": ["Coalesce", "Concat", "django.db.models.functions"],
        "category": "Functions",
    },
    # 7. Model Meta & Setup
    {
        "query": "How to define a custom database table name in Model?",
        "expected_keywords": ["db_table", "class Meta"],
        "category": "Modelling",
    },
    {
        "query": "How to create a multi-column unique constraint?",
        "expected_keywords": ["UniqueConstraint", "unique_together", "class Meta"],
        "category": "Modelling",
    },
    # 8. Performance & Miscellaneous
    {
        "query": "How to check the actual SQL query generated by QuerySet?",
        "expected_keywords": [".query", "print(queryset.query)"],
        "category": "Misc",
    },
    {
        "query": "How to use only() or defer() to limit loaded fields?",
        "expected_keywords": ["only(", "defer(", "performance"],
        "category": "Misc",
    },
]


async def evaluate() -> None:
    """하이브리드 검색 및 Late Interaction 리랭킹 품질을 골든 데이터셋으로 평가합니다."""
    search_service = get_search_service()

    total_queries = len(GOLDEN_DATASET)
    hit_at_3 = 0
    mrr_sum: float = 0.0

    print(f"--- Search Quality Evaluation (Total Queries: {total_queries}) ---\n")

    for entry in GOLDEN_DATASET:
        query: str = str(entry["query"])
        expected: list[str] = entry["expected_keywords"]  # type: ignore

        # 통합 검색 실행
        results = await search_service.search(query, limit=5)

        found_rank = 0
        is_hit_3 = False

        for i, res in enumerate(results):
            rank = i + 1
            content = res["content"]

            # 정답 판별 (키워드 매칭 방식)
            is_correct = any(kw.lower() in content.lower() for kw in expected)

            if is_correct and found_rank == 0:
                found_rank = rank
                if rank <= 3:
                    is_hit_3 = True

        if found_rank > 0:
            mrr_sum += 1.0 / found_rank
        if is_hit_3:
            hit_at_3 += 1

        print(f"[{entry['category']}] Query: {query}")
        print(
            f"Rank: {found_rank if found_rank > 0 else 'N/A'}, Hit@3: {'Yes' if is_hit_3 else 'No'}"
        )
        print("-" * 20)

    # 지표 계산
    final_mrr = mrr_sum / total_queries
    final_hit_rate_3 = (hit_at_3 / total_queries) * 100

    print("\n[Final Metrics]")
    print(f"- MRR: {final_mrr:.4f} (Target: > 0.75)")
    print(f"- Hit Rate@3: {final_hit_rate_3:.2f}% (Target: > 90%)")

    # 헌법(v2.0.0) 기준 평가
    if final_mrr >= 0.75 and final_hit_rate_3 >= 90:
        print("\n✅ Search quality meets the project constitution standards.")
    else:
        print("\n⚠️ Search quality is below the target goals. Further tuning required.")


if __name__ == "__main__":
    asyncio.run(evaluate())
